WWAWing/WWAWing

package.json

`npm install` と `npm run build` をそのまま実行した際に、TypeScriptが無いとエラーが発生しました。
package.json を見たところ、TypeScriptの欄が無いため追加しました。

TypeScriptがインストールされるようにpackage.jsonを修正

---

src/wwa_main.ts

バグ報告掲示板にて?という名前でお世話になりました。こちらでも厄介になります。
2年前に見つけた不具合報告を失念したまま忘れてしまったため、W3.15dβ2にて再度確認の上で報告いたします。
WWAWのバージョンはW3.15dβ2　動作環境はFirefox Developer Edition 57.0です。
WWAのバージョンは3.11　Javaのバージョンは1.8です。
システムメッセージの表示に本家と違いがあります。
物を買うときに所持金が足りない場合のメッセージ
WWA Wing「所持金が足りない。」
WWA「所持金がたりない。」
物を売るときにアイテムを持っていない場合のメッセージ
WWA Wing「アイテムをもっていない。」
WWA「アイテムを持っていない。」
物体「物を売る」からアイテムが持ちきれない時に表示するメッセージが、
「物を売るときにアイテムを持っていない場合のメッセージ」に設定されています。
また、BLANKの判定についても「物を売るときにアイテムを持っていない場合のメッセージ」でした。
WWAでは、この場合「アイテムがこれ以上持てないときの確認メッセージ」です。
マップ作成ツールでシステムメッセージを変更しないとこの現象は確認できないので注意してください。

システムメッセージの問題

---

packages/engine/src/wwa_main.ts

BGMを流したあと、パスワードセーブして、ロードしたときにBGMが復元されなかったため、
保存するようにする。

fix(audio): BGM読み込みなしのときもBGMを記憶する

---

.gitignore

WebStormとかのJetbrains系のIDEを使用した際に生成される `.idea` とビルドの成果物である `wwa.long.js` が `.gitignore` に含まれていないです。
このPull requestは `.gitignore` にこれらのファイルを追加したものです。

.gitignoreに.ideaとwwa.long.js系を追加

---

packages/assets/style/wwa_classic.css

クラシックモードのCSSに、プログレスバーのようなカバー画像と一緒に付く部品のCSSセレクタが付いていません。
そのため、下記画像のように、上部に読み込み状況のメッセージが表示されてしまいます。この場合、WWA外側(ページ下部)に書いてあるテキストは隠れてしまいます。
このプルリクエストはそのCSSセレクタを追加する形で修正するものとなります。

クラシックモードのCSSにカバー部品のセレクタを追加

---

packages/engine/src/wwa_main.ts

「プレイヤー追尾」「逃げる」移動属性パーツの移動先座標の候補生成処理が抜けてしまっていたので修正
- PLiCyさんの最終版、マージ前のdevelopの関数の処理内容が同一
- スタンダードマップの「レッツダンシン！」が正常に動く

fix(_getCandidateCoord): パーツの移動候補処理が消えていたので直す

---

packages/engine/src/wwa_data.ts
packages/engine/src/wwa_main.ts

- mapIDTableをWWAData(セーブデータ)から外す
close #79 
(Chrome 72 Mac)

fix(mapIDTable): パスワードセーブが重い件を修正 

---

packages/engine/src/wwa_main.ts

マージミスと思われます: https://github.com/WWAWing/WWAWing/commit/227b2784f4e1659d72038df0431cdd83a5b10fb4#diff-0891ded59d04cf6617a425ea86b9bfcfR1953
PLiCy版にも同様の不具合が入っていると思われます
close #102

fix(_drawPlayer): ゲーム開始時やジャンプゲート移動後にプレイヤーの足踏み動作が入らない

---

package-lock.json
packages/engine/src/wwa_main.ts

`$effitem=0` 時にステータス欄が凹まないようにします。（WWA 3.10に準拠する挙動になります）
凹ませる処理の関数の冒頭部で、早期returnを行うことにより、 凹ませ処理自体が走らなくなります。
凹ませを解除する処理は `$effitem`  の有効/無効関わらず実行します。これは、ステータス変化により凹んだ直後に `$effitem=0` を実行するとステータス欄が凹みっぱなしになるためです。
closes #93

fix(effitem): effitem=0時にステータスが凹まないようにした

---

packages/engine/src/wwa_main.ts

メッセージ（パーツの他、システムメッセージ含む）ダイアログの行頭の空白文字（半角スペースやタブなど）がCSSのスタイル都合で省略されてしまう不具合に対応します。
ついでに重複しているコードの共通化などを行っています
Chrome 73 Windows / Firefox 65 Windows

fix(updateCSSRule): メッセージの先頭にある空白文字がスタイル上表示されない問題

---

packages/assets/style/wwa_classic.css

[cherry-pick] クラシックモードのCSSにカバー部品のセレクタを追加

---

lerna.json
package-lock.json
package.json
packages/engine/package-lock.json
packages/engine/package.json
packages/loader/package-lock.json
packages/loader/package.json

機能アップグレードによる開発環境の改善
- lerna を 3.x (今回は 3.13.1)にアップグレード
- npm-run-all を 4.1.5 にアップグレード
- アップグレードに伴う設定ファイルの書き換え

refactor: Lernaを3.xにアップグレード

---

packages/engine/src/wwa_main.ts

- FirefoxでローカルでHTMLを開いたときにalertを出さない
- Firefox以外で開いたときに「Firefoxだと開ける」旨の文言を追加
- WWA Debugger -> wwa-server

chore(wwa_main): Firefoxローカル起動時にalertを出さない

---

package-lock.json
packages/assets/html/manual.html
packages/build-utils/package.json
packages/engine/package.json
packages/engine/src/wwa_main.ts

close #146 
Firefox 起動時は次の1文を追加
`Firefoxの場合も、バージョン68以降はローカルのHTMLファイルを直接開いた場合、通常起動できないことを確認しております。`

fix(local): Firefox68対応

---

package-lock.json
package.json
packages/engine/package-lock.json

READMEの通りにすると、sassが生成されなかったので、rootのpackage.jsonの `npm run build` でsassまで生成するようにしました。
本当はts-nodeでTypeScriptをJavaScriptにする作業を（見た目上）省略できるのが理想だと思いますが、それは私の方で進めようと思います。

fix(npm-script): npm run build で でsassのコンパイルもする

---

netlify.toml
packages/debug-server/package.json

- Windows で `npm run boostrap` を実行すると、 debug-server の nexe の実行に失敗するため (下記参照)
```
> @wwawing/debug-server@3.2.3 generate C:\WWAWing\packages\debug-server
> mkdir -p bin && nexe --target=win32-x86-8.6.0 --cwd . --output bin/wwa-server.exe
サブディレクトリまたはファイル -p は既に存在します。
処理中にエラーが発生しました: -p
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @wwawing/debug-server@3.2.3 generate: `mkdir -p bin && nexe --target=win32-x86-8.6.0 --cwd . --output bin/wwa-server.exe`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @wwawing/debug-server@3.2.3 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
- Netlify で build が2回実行されてしまう不具合の修正

fix(debug-server): package.json の generate コマンドに shx を追加

---

packages/engine/src/wwa_main.ts

closes #121 
ゲームオーバー時に、ゲームオーバー前に実行予定だったマクロ情報を破棄し、不正な物体配置が起こらないようにします。

fix(gameover): ゲームオーバー前に予約しているマクロを破棄する

---

packages/styles/src/core/_window.scss

`feature/plicy-2019` #175 向けです。
PLiCyバージョンより、複数QuickSaveのスタイルを移植します。
WingはSassになっているので、書き方を改めています。
ステータスなどが出ないのは後続のコミットを取り込んでいないからなので、後々直ります

feat(_window): 複数QuickSaveのsass移植

---

netlify.toml

engine に差分がない時 (READMEや設定などの書き換え)にプレビューを作成するのをやめます。
主に課金対策です。
下位パッケージ（Loaderなど)を更新したときにプレビューが作成されないのは目をつむってください... 🙇 
参考: https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds

build(netlify): engineに差分がないときにプレビューを作成しない

---

packages/engine/src/wwa_main.ts

`$save=1` でセーブ禁止にした時に、QuickSave保存のDOMが複数生成される不具合を修正します
修正前
修正後
b651572 からの部分cherry-pickです

[cherry-pick] 4Saveでクイックセーブ禁止時の不具合を修正

---

README.md

Wiki のコントリビューションガイドラインがリポジトリに移転したため、 README.md も変更後のURLとテキストに更新します。

README.md のコントリビューションガイドラインのURLを変更

---

packages/engine/src/wwa_main.ts

存在しない効果音が見つかった後に、BGMの再生処理が入ると2重で再生されることがあるため、そのための修正になります。
まだ動作確認は行っていないので、近いうちに行います。

[fix] BGMの再生処理をBGM以外で起こさないように修正

---

packages/engine/src/wwa_data.ts

fix(user-device): iPadOS 上 Safari がデフォルトでPC扱いされる不具合

---

packages/engine/src/wwa_save/WWASaveDataLogList.ts

Close: #295 
開発モードで packages/engine/lib/ 下の Standard Map (wwamap.html) を編集し、 `data-wwa-autosave=0` に差し替えた状態で動作確認をしました。

fix(engine): data-wwa-autosave=0 の有効化

---

README.md
packages/assets/html/manual.html

Microsoft Edge レガシ (レンダリングエンジン EdgeHTML 18以下) は 本日 2021-03-09 をもって Microsoft 社によるサポートが終了するため、WWA Wing としても、次回のリリースよりサポートを取りやめます。
Edge対応のための機能は今後順次削除予定ですが、本PRではマニュアルのサポートブラウザの内容のみを変更します。

docs: Edge レガシのサポート終了

---

.gitignore
package.json
packages/event-emitter/package.json
packages/event-emitter/tsconfig.json
packages/event-emitter/tsconfig.module.json
packages/loader/package.json
packages/loader/tsconfig.json
packages/loader/tsconfig.module.json
packages/page-generator/package.json
packages/page-generator/tsconfig.module.json

event-emitter, loader, page-generator の3パッケージについて、ES Module (module下） と  CommonJS (lib下)の並行publishとします。
WWA Maker (Electron なので CommonJSが必要) と WWA Wing (Webpackの Tree Shakingを効かせたいので ES Moduleがほしい)の双方の要望に応える形としました

build(module): CommonJS, ESModule 並行publish

---

.github/workflows/release.yml

#361 でSSHキーが不要になったので、secretsから削除するとともに、ワークフローからも削除します

refactor(release): SSHキーのセットアップをやめた

---

packages/engine/src/wwa_main.ts
packages/loader/src/core/text-loader/index.ts
packages/loader/src/infra/index.ts

Restart Gameをしたときに初期化されないケースがあるので、Loaderで初期化することで、restartDataに入るようにします

fix(loader): ユーザ変数・プレイ時間・スピード変更許可フラグ初期化をloaderへ移動

---

packages/engine/src/wwa_main.ts
packages/engine/src/wwa_message.ts
packages/engine/src/wwa_parts_player.ts

#394 で show_str が早期に処理されるようになったのはよかったのだが、ユーザ変数が埋まった状態で更新されるようになっていたので、それらが更新された時にリアルタイムにメッセージウィンドウに記録されるようにする。

fix(show-str): show_strマクロの変数がリアルタイムに更新されるようにした

---

packages/all/scripts/make-wwawing-dist.ts
packages/engine/debug/make-debug-pages.ts
packages/engine/src/wwa_data.ts
packages/engine/src/wwa_main.ts
packages/page-generator/src/data-types/wwa.ts
packages/page-generator/src/index.ts
packages/styles/src/core/_vardump.scss

- 旧来のtableでの変数一覧表示で、添字をマウスホバーで説明を表示できるようにします
- 変数一覧ファイルの取得に失敗した場合にエラー表示します
- 整合性の関係で、スタンダードマップ以外では変数一覧を非表示にします

feat(vardump): ユーザ変数の説明ラベルを旧来の変数一覧でも表示

---

package-lock.json
packages/debug-server/package.json

pkg で指定している 16.13.2 のバージョンが存在しないようで、 GitHub Actions の Publish で落ちてしまうようなので、取り出す Node のバージョンを 16 に変更しました。
また、発生する pkg のバージョンは 5.6.0 なので pkg のバージョンも変更しています。

fix: pkg のバージョンと扱う Node のバージョンを変更

---

packages/engine/src/wwa_password_window.ts

https://user-images.githubusercontent.com/12381375/175762846-d1587830-e1f9-4c70-9c4b-962caaae62fe.mov
- Close: #275 
- パスワードセーブの画面に「コピー」ボタンを追加します。
- 「コピー」ボタンを押すと「コピーしました」にテキストが代わり、１秒後にもとに戻ります。

コピーボタンの機能追加

---

packages/engine/src/wwa_data.ts
packages/engine/src/wwa_main.ts
packages/engine/src/wwa_message.ts

- マクロ実行中に新規のメッセージが表示されようとしている場合は、  `this._pages` に詰め直すことで、メッセージが閉じられてから表示されるよう変更
- close #212
- マクロ実行中にゲームオーバーが発生する場合は、メッセージ処理を実行しないよう変更

fix(wwa-message): マクロ実行中にメッセージやゲームオーバーが発生した場合の対処

---

packages/engine/src/wwa_message.ts

$delay_sound とよく似ていますが、こちらは結果を保存せず、その実行でのみ再生を遅延させます。

feat(sound): soundマクロでBGM遅延再生に対応

---

packages/common-interface/src/wwa_system_message.ts
packages/engine/src/wwa_main.ts

以下のシステムメッセージに対してデフォルト値（ON, OFF, DEFAULTの設定含む）が適用されていなかったので修正します。
- `CONFIRM_LOAD_SOUND` (効果音・ＢＧＭデータをロードしますか？)
- `ITEM_SELECT_TUTORIAL` (このアイテムは%HOW_TO_USE_ITEM%ことで使用できます。使用できるアイテムは色枠で囲まれます)
- `CONFIRM_ENTER_URL_GATE` (他のページにリンクします。よろしいですか？)
また、アイテム使用メッセージが出るべきところでアイテム使用可能メッセージが表示されることがあったので修正します。

fix(system-message): システムメッセージのデフォルト値が適用されない不具合を修正

---

packages/engine/src/wwa_main.ts
packages/engine/src/wwa_parts_player.ts
packages/engine/src/wwa_play_time.ts

- 経過時間がゲーム起動時からのフレームカウントになっており、セーブデータと連動していなかったため、TIMEと同等の時間を使うように変更します。
- 本来はフレームカウントを利用したほうがよかったかもしれませんが、TIMEがDateの引き算で実装されている関係で、そちらに統一させていただきます。
- TIMEの計算が複雑化していたのでクラスに機能を集約するリファクタを実施しました。

fix(play-time): 経過時間が正しく表示されない不具合を修正・リファクタ

---

packages/assets/script/defined.js
packages/common-interface/src/wwa_system_message.ts
packages/engine/src/wwa_data.ts
packages/engine/src/wwa_expression2/converter.ts
packages/engine/src/wwa_expression2/eval.ts
packages/engine/src/wwa_expression2/wwa.ts
packages/engine/src/wwa_main.ts
packages/engine/src/wwa_monster.ts
packages/engine/src/wwa_parts_player.ts

従来のアルテリオス計算式でダメージ計算式を定義する場合には以下を記述
```
/**
* プレイヤーから敵に与えるダメージ計算式
*/
function CALC_PLAYER_TO_ENEMY_DAMAGE() {
v["tmp_enemy_damage"] = (AT - ENEMY_DF)
if(v["tmp_enemy_damage"] > 0) {
ENEMY_HP = ENEMY_HP - v["tmp_enemy_damage"];
}
}
/**
* 敵からプレイヤーに与えるダメージ計算式
*/
function CALC_ENEMY_TO_PLAYER_DAMAGE() {
v["tmp_player_damage"] = (ENEMY_AT - DF)
if(v["tmp_player_damage"] > 0) {
HP = HP - v["tmp_player_damage"];
}
}
```

ダメージ方程式をユーザカスタム関数でカスタマイズできるようにしました

---

packages/engine/src/wwa_main.ts

配列のシャローコピーが原因で、DBから直接セーブデータをロードしないケースで値がロードできない不具合を修正します

fix(save): ユーザ変数が正しくロードできない不具合を修正

---

packages/engine/src/wwa_expression2/converter.ts
packages/engine/src/wwa_expression2/eval.ts

`$face` マクロの機能を WWA Script の関数として追加します。
下記の通りに実行すると、 `MSG` 関数で `FACE` 関数に指定したイメージが表示されます。
```
FACE(80,140,7,15,2,2);
FACE(280,140,5,15,2,2);
MSG("Ｖｅｒ３．１から頻出処理である\nイベント時の顔画像表示をサポートするマクロ文を追加しています。");
```
現時点では `MSG` 関数による改ページには対応していません。 `MSG` の後に `FACE` 関数を実行しようとした場合は、 Script 文の中のすべての `FACE` 関数のイメージが最初のメッセージに表示されます。
（今後解消する予定です。）
```
FACE(80,140,7,15,2,2);
FACE(280,140,5,15,2,2);
// ここで下2つの FACE もまとめて表示される
MSG("Ｖｅｒ３．１から頻出処理である\nイベント時の顔画像表示をサポートするマクロ文を追加しています。");
FACE(100,140,7,15,2,2);
FACE(260,140,5,15,2,2);
// ここは何も FACE が表示されない
MSG("「＝」のあとに表示するＸ座標、\nＹ座標（ドット単位です。注意）\nそのあとに表示元画像のＸ座標、\nＹ座標（こちらはパーツ単位です）\nそのあとに画像のＸ方向の幅、\nＹ方向の幅（パーツ単位）で\n指定します。");
```

【WWA Script】 $face マクロ相当の機能を WWAScript の関数として追加

---

packages/engine/src/wwa_data.ts
packages/engine/src/wwa_estimate_battle.ts
packages/engine/src/wwa_main.ts
packages/engine/src/wwa_parts_player.ts

- カスタムダメージ関数で数値でない値を返したり、値を返さなかったりした場合にフリーズしないようにしました
- 戦闘予測時にプレイヤー生命力が0より小さくなったあとに中断された場合に勝負がつかない判定になる詐欺結果と、戦闘前にプレイヤーの生命力が0の場合に戦闘予測の結果が詐欺気味になるのを修正しました

fix(battle): 戦闘関連のフリーズと予測詐欺を軽減

---

packages/engine/src/wwa_expression2/acorn.ts
packages/engine/src/wwa_expression2/converter.ts
packages/engine/src/wwa_expression2/eval.ts
packages/engine/src/wwa_expression2/wwa.ts
packages/engine/src/wwa_main.ts
packages/engine/src/wwa_picture/WWAPicture.ts

ピクチャ機能のプロパティの変換方法を変更します。
これまではプロパティを JSON.parse で変換していましたが、これからは WWAScript の Acorn と同じシステムで変換するようにします。
- プロパティの名前に引用符書くのがダルい
- テキストの改行文字問題（テンプレート文字列では直接 `\n` で書けない）
- 最後のプロパティでカンマ必要なのかよく分からない
- 今後ステータスや変数を連動して表示する際の準備（関連: #689 ）
ほぼほぼ大丈夫かと思います。
JavaScript では JSON のテキストをそのまま貼り付けてもオブジェクトとして解釈してくれるので、 Acorn も同じように解釈されると思います。
今のところテストマップのすべてのプロパティは稼働できています。

feat: 【ピクチャ機能】プロパティをオブジェクト形式で表記できるようにする

---

packages/engine/src/wwa_expression2/converter.ts
packages/engine/src/wwa_expression2/eval.ts
packages/engine/src/wwa_main.ts

指定した物体・マップIDを指定することによりマップチップ上の画像の座標を取得できます。
PICTURE機能支援関数になります。
* 構文: `GET_IMG_POS_X(parts_id, is_object, is_first_motion)` 
`is_object=0: 物体`
`is_object=1: 背景`
is_first_motion は物体を指定したときのみ有効。
物体パーツは2つの画像で構成されているため、`is_first_motion=0` で1つ目の画像のX/Y座標を、`is_first_motion=2` で2つ目の画像のY座標を取得する。
スタンダードマップの赤枠で囲った座標の画像座標を取得する例
```
// 物体パーツの画像座標を取得
v[0] = o[2][1];
v[1] = GET_IMG_POS_X(v[0], 0, 0) // 80
v[2] = GET_IMG_POS_Y(v[0], 0, 0) // 440
v[3] = GET_IMG_POS_X(v[0], 0, 1) // 80
v[4] = GET_IMG_POS_Y(v[0], 0, 1) // 480
// 背景パーツの画像座標を取得
v[5] = m[2][1];
v[6] = GET_IMG_POS_X(v[5], 1) // 80
v[7] = GET_IMG_POS_Y(v[5], 1) // 160
```
* 引数省略時の挙動
```
v[0] = o[2][1];
v[1] = GET_IMG_POS_X(v[0], 0) // 80
v[2] = GET_IMG_POS_Y(v[0], 0) // 440
v[1] = GET_IMG_POS_X(v[0]) // 80
v[2] = GET_IMG_POS_Y(v[0]) // 440
```

feat: 【WWA Script】指定したIDパーツのマップ画像上のIDを取得出来る関数を実装しました

---

packages/engine/src/wwa_expression2/converter.ts
packages/engine/src/wwa_expression2/wwa.ts

#689 で `X` と `Y` 、 `ID` 、 `TYPE` から実行元パーツ情報を WWA Script で取得できるようになりましたが、この定数に対して代入できるような設計になっていたので修正します。
現在のバージョンでも代入はできないのですが、「未実装の要素です」と出力されていて、あたかも代入で改変できそうな挙動をしていたので、できないようにエラーメッセージの内容と出力経路を変更します。
修正後ではこんな感じでエラーが発生します。

feat: 【WWA Script】 実行元パーツ情報の代入を禁止するように修正

---

packages/all/scripts/make-wwawing-dist.ts

wwa.js は minify されているので、改行コードがCRLFである必要がないのですが、改行コードがCRLFだとwwa.jsが Windows Defender にトロイの木馬と判定されることがあるため、改行コードをLFに変更します。

fix(make-wwawing-dist): wwa.js の改行コードを CRLF から LF に変更した

---

packages/engine/src/wwa_message/data/node.ts

マルウェア誤検知の原因と思しきコミットを一旦 revert します
This reverts commit 39471e669d1449ebc7d79495a987343f4628f4b0.

Revert "fix(node): triggerPartsの渡し漏れを修正"

---

packages/engine/src/wwa_main.ts
packages/engine/src/wwa_message/_internal/index.ts
packages/engine/src/wwa_message/data/index.ts
packages/engine/src/wwa_message/data/node.ts
packages/engine/src/wwa_message/data/page.ts
packages/engine/src/wwa_message/index.ts

WWA Script 正式化に向けての最も大きな壁である WWA Script 実行タイミングの変更PRです。
主に以下の観点からの動作確認が必要です
- 挙動としては正しそうですが、MSGを呼んだ場合の挙動はかなり不安定なので今後改善します
- 以前は空メッセージスコア＋MSGの場合はMSGが無視される挙動だった

feat(message): WWA Script 実行タイミングの変更

---

packages/engine/src/wwa_message/data/node.ts

#704 の対応の影響で、 `triggerParts` の渡し忘れで実行元パーツ情報が正しく出力されなかったので修正しました。
テストマップにて、実行元パーツ情報や位置が正しくセットされていることを確認。

WWA Script の X/Y/ID/TYPE が機能しない不具合の修正

---

packages/engine/src/wwa_picture/WWAPicture.ts
packages/engine/src/wwa_picture/WWAPictureItem.ts
packages/engine/src/wwa_picture/WWATimer.ts
packages/engine/src/wwa_picture/utils.ts

- #708 で書いてあった「`time` プロパティを複数記載できるようにしましたが、2番目の効力は今のところ実装していません。」の実装対応を行います。
- `animTime` プロパティの機能を実装します。
```
{
animTime: [100, 200],
}
```
アニメーションの実行時間を指定します。ピクチャ生成時にカウントが始まり、一つ目の値を過ぎるとアニメーションが開始され、二つ目の値を過ぎるとアニメーションが止まります。
- `time` プロパティとは開始と終了の関係が逆です。取り扱いにご注意ください。
- `time` プロパティの開始時間前で非表示の間でもカウントは始まっています。例えば下記のような指定方法では、アニメーションは動きません。
```
{
time: [1000, 100], // 100ms でピクチャ表示、 1100ms でピクチャ消去
animTime: [10, 50] // 10ms でアニメーション開始、 50ms でアニメーション終了
}
```
- 一つ目の値が二つ目よりも小さい場合は、アニメーションは動きません。うんともすんとも言いませんが、逆手に利用して、変数制御で条件付きでアニメーションを起こさない仕掛けを作ることはできます。
```
{
animTime: [100, 50], // これは動きません
}
```
- フレーム時間版もあります。 `animTimeFrame` でどうぞご活用ください。スネークケースで `anim_time_frame` でも書けます。

feat: ピクチャ機能の time プロパティの開始時間指定と animTime プロパティの機能を実装

---

packages/engine/src/wwa_expression2/eval.ts

WWA Script の PARTS 関数は4番目の引数に、画面内のパーツに限定して置き換えるかのフラグがあります。 0 だとマップ内のパーツを全部置き換え、 1 だと画面内のパーツに限定して置き換えを実行します。
マクロ文にある `$parts` マクロだと 0 が規定値ですが、 WWA Script の方は 1 が規定値になっています。
https://github.com/WWAWing/WWAWing/assets/12381375/2bf480c3-ccff-4955-b168-56060a7b9707
マクロ文の仕様で差異があるのはまずいので、この問題を修正します。
https://github.com/WWAWing/WWAWing/assets/12381375/3d96e343-fc9e-47b0-bbe0-da08b634b024

【WWA Script】PARTS 関数の画面内限定フラグの規定値がマクロ文と異なる問題の対応

---

packages/engine/src/wwa_picture/WWAPictureItem.ts

**仕様変更が発生します。**
現在の `text` プロパティの描画位置はテキストのベースラインを基準としています。アルファベットをメインに使用する環境では違和感はないですが、日本語では馴染みがなく、思った通りに描画できない（背景にステータス枠を使用して〜、テキストはその左上から余白を考慮してこのくらいにして〜、を想像しながら設定しにくい）ので、描画位置の基準をテキスト上端に変更します。
普通にテキストだけ描画している場合、位置がちょっとズレるので問題はないと思いますが、テキストとその背景を同時に描画している場合は、テキストが下にずれ込むことになると思います。適宜修正をお願いします。
```
PICTURE(1, {
pos: [100, 100],
text: "hogehoge",
img: [1, 2],
});
```
こんな感じに動きます。

【ピクチャ機能】テキストの描画基準をテキスト上端に変更する

---

packages/engine/src/wwa_expression2/__tests__/symbols-test.ts
packages/engine/src/wwa_expression2/converter.ts
packages/engine/src/wwa_expression2/eval.ts
packages/engine/src/wwa_expression2/symbols/index.ts
packages/engine/src/wwa_expression2/symbols/player_coord_pixel.ts
packages/engine/src/wwa_expression2/wwa.ts
packages/engine/src/wwa_main.ts

**WWA Script の定数機能追加ですが、マージ先はピクチャ機能になります！！**
現在のプレイヤーの座標は `PX` と `PY` で算出できますが、ピクチャ機能で使用した場合、画面下端あるいは画面右端にプレイヤーがいる場合は正確に算出できない問題があります。
```js
{
// 画面右端あるいは下端にいるとなぜか 0 になる
pos: ([PX % 10) * 40, (PY % 10) * 40],
}
```
これは画面端はプレイヤーの座標は同じだけど、プレイヤーの描画場所が異なるためです。
この場合はカメラ座標を算出すれば良いんですが、ほとんどの場合プレイヤーの画面内座標を使用したいため、プレイヤーの画面内座標を算出する定数を実装しました。
（カメラ座標も必要であれば実装するつもりです）
```js
{
pos: [PLAYER_PX, PLAYER_PY],
}
```
こんな感じで算出されます。
WWAeval で言う `ToPixelXY` 関数相当の機能をします。

【ピクチャ機能】プレイヤーの画面内座標を算出する PLAYER_PX/PY を実装

---

packages/engine/src/wwa_picture/utils.ts

`text` プロパティに数値形式を使用すると `Uncaught TypeError: t.split is not a function` とエラーで止まる不具合が発生したので修正しました。
原因はプロパティを適切な形式に変換する過程の前でバリデーションが行われ、そのバリデーションで弾かれるとそのままの値が使用されていたことでした。
そして `text` プロパティでは改行対応で `"\n"` 区切りで各行分割していたので、その処理に引っかかってエラーになりました。
今回の修正は `text` プロパティに焦点を当てていますが、 `textAlign` などの文字列形式のプロパティも数値形式を文字列形式に変換するようになっているので、安定して動作できると思います。
なお、文字列形式のプロパティに数値形式が入った場合、下図のように一応警告が出てきます。
将来は文字列も数値も容認できるプロパティと、文字列しか認めないプロパティに区分けしようかなと考えています。
↓ 検証に使用した WWA Script のコード
```
PICTURE(1,{
pos: [100, 100],
text: 123,
font: "20px sans-serif",
lineHeight: 20,
textAlign: "center"
})
```

【ピクチャ機能】 text プロパティで数値形式が使用できない問題の修正

---

packages/engine/src/wwa_picture/WWAPicture.ts

ピクチャの定義ファイルがない場合のエラーがプレイヤーにも大々的に見えてしまっているので、consoleに出す程度に抑えます

feat(picture): ピクチャ系のエラーをwindow.alert -> console.warn に変更

---

packages/all/scripts/make-wwawing-dist.ts

不安定版の完全版に WWA Script を使用する上で必要になる以下のファイルが欠けていたため追加しました。
- script_file_list.json
- script/index.js
- script/defined.js
ピクチャ機能では上記のファイルがないとテストマップの一部サンプルが動かないため、このプルリクエストマージ後はピクチャ機能のブランチ (#682) にも取り入れます。
https://github.com/user-attachments/assets/28164ff3-07c7-4d23-926d-4059540eb21e

fix(WWA Script): WWA Script付きの完全版にScript関連のファイルを含める

---

packages/assets/script/defined.js
packages/engine/src/wwa_camera.ts
packages/engine/src/wwa_expression2/converter.ts
packages/engine/src/wwa_expression2/eval.ts
packages/engine/src/wwa_expression2/wwa.ts
packages/engine/src/wwa_main.ts
packages/engine/src/wwa_parts_player.ts

https://github.com/user-attachments/assets/a7548e48-3353-4cd5-95bc-6162a3ea2dfd
それぞれカメラ画面の左上端の座標を X, Y で取得します。
例えばプレイヤーが X: 15, Y: 23 とした場合、 X: 10, Y: 20 で取得します。
このシンボルに代入はできません。
カメラ画面が移動し終わった時に実行されるユーザー定義イベント関数です。
この場合 "CX" と "CY" を使用すると、移動後の座標で取得します。
ピクチャ機能と併用することで、特定のパーツ上にのみ描画する動きが（一応）作れるようになります。

feat(WWA Script): WWAのカメラ座標を取得するシンボルとカメラ移動に発生するイベント関数を追加

---

packages/engine/src/wwa_main.ts

`data-wwa-title-img` が未指定だと指定していると誤判定してしまって起動しない問題が発生していました。
WWA コンストラクター内部では `undefined` の一方で、 start() 関数では `null` と扱っていて、比較も `===` だったため判別に失敗していました。

カバー未指定だとWWAが起動しない問題の修正

---

packages/engine/src/wwa_cgmanager.ts
packages/engine/src/wwa_picture/PictureCacheCanvas.ts
packages/engine/src/wwa_picture/WWAPictureItem.ts
packages/engine/src/wwa_picture/utils.ts

#799 の対応でピクチャの描画速度を早めるために一度ビットマップに変換する実装をしていました。
ただし一度に大量のピクチャを生成する場合、このビットマップの変換で描画が遅れ、レスポンスが劣化する事象が発生していました。
今回の対応でこのビットマップに変換する過程を削除します。
#799 にあった以下のサンプルコードを Firefox で試したところ、描画は遅れるものの、プレイヤーの操作レスポンスが速くなっていることは確認できています。
```
PICTURE(-1);
for (i = 0; i <= 21; i++) {
for (j = 0; j <= 21; j++) {
PICTURE(-1, {
pos: [i * 20, j * 20],
time: [10000 + j * 100, j * 100],
size: [20, 20],
img: [GET_IMG_POS_X(m[i][j], 1), GET_IMG_POS_Y(m[i][j], 1)],
});
}
}
```

【ピクチャ機能】 ピクチャ内部の Canvas からビットマップ画像に変換する処理を削除

---

packages/engine/src/wwa_main.ts

#798 のデグレード対応です。
ピクチャのデータが Object から Map に変わったことで、パーツからプロパティを読み込むピクチャが正しく表示されなくなっていました。

パーツからピクチャが表示されない不具合を修正

---

packages/engine/src/load_script_file/index.ts
packages/engine/src/wwa_expression2/eval.ts
packages/engine/src/wwa_main.ts
packages/engine/src/wwa_util.ts

- 存在しないプロパティにアクセスした場合のエラーメッセージを正しくする (現在はメッセージなしのエラーが出る)
- 配列の要素外アクセスをした場合に console.warn を出す
- 外部スクリプトの構文エラーをalert
- CALL_WWA_STARTのランタイムエラーをalert
- 文字列以外もMSGできるようにする
- 文字列の添字アクセスを可能にする (例: "abc"[1]  -> "b")
- 存在しない値にアクセスした場合に空文字列を返しているところをundefinedに変更

fix(eval): 添字アクセスのエラー表記改善・文字列の添字アクセスを可能に / WWA起動時のスクリプトエラー可視化

---

packages/engine/src/wwa_expression2/converter.ts
packages/engine/src/wwa_expression2/eval.ts
packages/engine/src/wwa_expression2/wwa.ts
packages/engine/src/wwa_main.ts
packages/engine/src/wwa_sound.ts

カスタムイベント関数『CALL_BGM_END』を実装しました。
- BGMを終わりまで再生したタイミングでイベントを発生させる関数です。
- このカスタムイベント関数を設定した場合、特定BGMを再生してから別のBGMを立て続けに流したりすることができます。
- 関数内では変数『SOUND_ID』を使用できます。（値：再生したBGMの番号）
- 一通りの動作確認済み。（CALL_BGM_ENDの有無 + SOUND(xx) / $sound=xx）
設定例
```
function CALL_BGM_END(){
if(SOUND_ID == 90){ //90:ループ曲用のイントロ部分用BGM→91:ループ部分
SOUND(91);
}
else{ //上記以外は同じBGMを再度呼ぶ
SOUND(SOUND_ID);
}
}
```
注意
- CALL_FRAMEと同じタイミングで再生終了したか確認します。
- WWAのタブがバックグラウンド状態になった場合、BGMの再生終了後にBGMがループしません。
- ※このカスタムイベント関数を設定していない場合、従来通りのBGMループ挙動となります。

CALL_BGM_ENDを実装
