src/wwa_main.ts
=> ./audio/ディレクトリの参照

packages/engine/src/wwa_main.ts, packages/engine/src/wwa_parts_player.ts
=> fix(setMessageQueue): モンスターとスコア表示で$mapマクロ実行の相対座標が動作しない

packages/build-utils/src/make-wwapage.ts, packages/debug-server/package-lock.json, packages/engine/package-lock.json, packages/loader/package-lock.json
=> fix(make-wwapage): 開発用WWAのページのCryptoJSのパス修正

packages/engine/src/wwa_camera.ts, packages/engine/src/wwa_cgmanager.ts, packages/engine/src/wwa_data.ts, packages/engine/src/wwa_estimate_battle.ts, packages/engine/src/wwa_inject_html.ts, packages/engine/src/wwa_input.ts, packages/engine/src/wwa_main.ts, packages/engine/src/wwa_message.ts, packages/engine/src/wwa_monster.ts, packages/engine/src/wwa_motion.ts, packages/engine/src/wwa_parts_player.ts, packages/engine/src/wwa_password_window.ts, packages/engine/src/wwa_psave.ts, packages/engine/src/wwa_util.ts, packages/loader/package-lock.json, packages/loader/package.json
=> PLiCyバージョンのマージ

package-lock.json, packages/engine/src/wwa_data.ts, packages/engine/src/wwa_main.ts, packages/engine/src/wwa_message.ts
278aac68a79bbc604ceeac859791a5a46d99f6dc の cherry-pick
QuickSave複数化が絡む処理は削除
=> [cherry-pick] デバイス判定用のCLASSを作成

getEngineVersion.sh
=> fix(getEngineVersion): バージョン取得機構がうまく動作していなかった

package-lock.json, packages/assets/html/manual.html, packages/build-utils/package.json, packages/engine/package.json, packages/engine/src/wwa_main.ts
v3.2.1 リリースの master -> develop バックポートです
=> Backport 190715

package-lock.json, package.json, packages/build-utils/package.json, packages/engine/package.json, packages/engine/src/wwa_data.ts, packages/engine/src/wwa_main.ts, packages/engine/src/wwa_message.ts, packages/engine/src/wwa_parts_player.ts
デフォの座標がハードコードされていた
Closes: #155
=> fix:  $imgframeでアイテムボックス背景の変更時、アニメーション中背景画像がデフォになる問題

package-lock.json, packages/styles/package.json
gitignoreで無視されていたされていた
filesフィールドをpackage.jsonに書いて、何を含むかを明示する。
=> fix(styles): CSSがnpm publish されていない問題を修正

packages/engine/src/wwa_data.ts, packages/engine/src/wwa_main.ts
=> useGameEnd 削除, Bottom_WWA_Buttonによるボタン出し分け

package-lock.json, packages/engine/src/wwa_main.ts
このPR単体では意味がありませんが、 #201 Phase3でセーブ圧縮を入れたときに、ウィンドウの初期化順序が変わるため、その部分だけ先行投入します
96c2713 からの部分cherry-pickです。
- メッセージウィンドウが出る
- スコアウィンドウが出る
- faceが表示できる
=> [cherry-pick] 再開時のメッセージウインドウnull参照エラーを回避するために宣言の位置を変更

package-lock.json, packages/engine/package.json, packages/engine/webpack.config.prod.ts, packages/loader/package.json
サポート切れてたので...
wwa.jsのライセンスコメントが出力されるところは確認しました
=> improve(wwa.js): use terser-webpack-plugin instead of uglifyjs-webpack-plugin

packages/common-interface/src/wwa_data.ts, packages/engine/src/wwa_main.ts, packages/engine/src/wwa_message.ts, packages/loader/src/infra/index.ts
=> feat(wwa_data): 歩数カウント追加

package-lock.json
This will reduce some major vulnerabilities.
=> Apply the result of `npm audit fix`.

LICENSE, packages/all/LICENSE, packages/assets/html/manual.html, packages/debug-server/LICENSE, packages/engine/LICENSE, packages/event-emitter/LICENSE, packages/loader/LICENSE, packages/loader/src/___debug-resources___/index.html, packages/page-generator/LICENSE
=> chore: 2021年あけましておめでとうございます

packages/all/scripts/upload-zip.ts
=> fix(upload-zip): zipのアップロードで型が通らなかった箇所の修正　(backport)

packages/engine/src/wwa_main.ts
パスワードセーブのキーが間違っていました
https://github.com/WWAWing/WWAWing/pull/330#issuecomment-821823422
=> fix(decode-password): パスワードロードに失敗する不具合を修正

packages/engine/src/wwa_main.ts, packages/engine/src/wwa_save/WWASaveDataDBList.ts, packages/engine/src/wwa_save/common/definitions.ts
https://github.com/WWAWing/WWAWing/pull/330#issuecomment-824127397
の対応です
=> fix(check-save-data-compatibility): 旧バージョンからのデータのセーブデータが持ち越せない不具合を修正

packages/all/scripts/update-sites.sh
マニュアルと同様に、頻繁に更新されるものなので、スタンダードマップも更新するようにします
=> build(update-sites): sites 更新時にスタンダードマップも更新する

.npmignore, package.json, packages/assets/.npmignore, packages/assets/package.json, packages/debug-server/.npmignore, packages/debug-server/package.json, packages/engine/package.json
publish されるファイルは package.json の files フィールドで指定されるべきなので、そうします
=> chore(npmignore): 削除

packages/engine/src/wwa_data.ts, packages/engine/src/wwa_main.ts, packages/engine/src/wwa_parts_player.ts
https://github.com/WWAWing/WWAWing/pull/92#issuecomment-922767512
=> fix(player): 移動速度変更メッセージが出ない不具合・戦闘が一部高速にならない不具合修正

packages/engine/src/wwa_main.ts
https://github.com/WWAWing/WWAWing/pull/92#issuecomment-922804322
=> fix(quicksave): X座標とアイテムが保存されない不具合修正

package-lock.json
=> Merge develop 2021 09 20

packages/assets/style/style.css, packages/engine/debug/make-debug-pages.ts, packages/page-generator/src/data-types/page.ts, packages/page-generator/src/index.ts, packages/page-generator/src/wwa.pug
XEの暫定対応。React版を作りたいが、リリースに間に合わなければこのまま出すことになる
（`data-wwa-var-dump-elm` 属性についてマニュアルで言及がないのは意図的です。）
=> feat(vardump): 変数一覧を表示できるようにした

packages/common-interface/src/wwa_data.ts, packages/engine/src/wwa_data.ts, packages/engine/src/wwa_main.ts, packages/engine/src/wwa_parts_player.ts, packages/loader/src/core/text-loader/index.ts, packages/loader/src/infra/index.ts
ステータスを隠した場合に、その状態がセーブされていなかったので、セーブデータに含めるようにします
=> fix(player): ステータスの表示状態がセーブされない不具合を修正

package-lock.json, package.json, packages/all/package.json, packages/common-interface/package.json, packages/debug-server/package.json, packages/engine/package.json, packages/event-emitter/package.json, packages/loader/package.json, packages/page-generator/package.json, packages/styles/package.json
=> fix(deps): 依存ライブラリアップデート

packages/engine/src/wwa_main.ts, packages/engine/src/wwa_parts_player.ts
`$show_str`  が指定されているパーツで変数が書き換えられた場合同様、スコア表示のパーツでステータスが書き換わった場合に、スコア表示内容を修正するものです。
=> fix(score): スコア表示パーツ自身でステータス変化があった場合にスコアを再計算する

README.md
=> docs(README): buildも忘れてた

package-lock.json, packages/page-generator/package.json
=> fix: pug-cli のアンインストールによるpugの脆弱性対応

lerna.json, netlify.toml, package-lock.json, packages/all/package.json, packages/assets/package.json, packages/common-interface/package.json, packages/debug-server/package.json, packages/engine/debug/make-debug-pages.ts, packages/engine/package.json, packages/engine/src/wwa_main.ts, packages/event-emitter/package.json, packages/loader/package.json, packages/page-generator/package.json, packages/styles/package.json
変数の中身を見て0とすべきところをindexが0かどうかを見ているバグがありましたので修正してhotfixします。
=> リリース v3.7.1 / fix(var-div): ゼロ除算の結果が仕様通りにならない不具合を修正

package-lock.json, package.json, packages/all/package.json, packages/common-interface/package.json, packages/debug-server/package.json, packages/engine/package.json, packages/engine/src/json_api_client/index.ts, packages/engine/src/wwa_audio/WWAAudio.ts, packages/engine/src/wwa_audio/WWAWebAudio.ts, packages/engine/src/wwa_data.ts, packages/engine/src/wwa_main.ts, packages/event-emitter/package.json, packages/event-emitter/src/impl/browser/index.ts, packages/loader/package.json, packages/loader/src/___debug-resources___/demo-browser.ts, packages/loader/src/___debug-resources___/demo-node.ts, packages/loader/src/core/index.ts, packages/loader/src/core/map-data-client/BaseMapDataClient.ts, packages/loader/src/core/map-data-client/BrowserMapDataClient.ts, packages/loader/src/core/map-data-client/NodeLocalMapDataClient.ts, packages/loader/src/core/map-data-client/index.ts, packages/page-generator/package.json, packages/styles/package.json
XMLHttpRequest の利用箇所3箇所を fetch に移行します。
- WWALoader の マップデータロード処理
- 変数名一覧取得処理
- 効果音取得処理 (WebAudioの方)
- Audioタグの方もIE11移行で不要になりますが、別PRでやります。
=> refactor(loader): XHR から fetch に移行

packages/engine/src/wwa_data.ts, packages/engine/src/wwa_main.ts, packages/engine/src/wwa_symbol_parser/index.ts, packages/engine/src/wwa_symbol_parser/parsers.ts, packages/engine/src/wwa_symbol_parser/value-assign-operation.ts
wwa_main.ts から set マクロのパースに関する処理だけ切り出しました。
=> refactor(symbol-parser): setマクロのパース処理を切り出した

packages/engine/src/wwa_data.ts, packages/engine/src/wwa_main.ts, packages/engine/src/wwa_message.ts
- `<P>` で終わるときにうまく動かないが、スコア表示固有の問題じゃなさそうなので別PRでやります
=> feat(score): 新スコア表示実装

packages/engine/src/wwa_message.ts
=> fix(parse-macro): show_str系マクロでのスペース除去を改善

packages/assets/script/index.js, packages/assets/script/script_file_list.json, packages/engine/src/load_script_file/index.ts, packages/engine/src/wwa_expression2/acorn.ts, packages/engine/src/wwa_expression2/converter.ts, packages/engine/src/wwa_expression2/eval.ts, packages/engine/src/wwa_expression2/wwa.ts, packages/engine/src/wwa_main.ts
こちらから分岐しています
* #601 
* `script_file_list.json` にユーザー定義スクリプト一覧を記述し、記載されているファイルをユーザ定義関数として読み込めます
* `script_file_list.json` に以下を記述する
```
[
"./script/index.js",
"./script/lib.js"
]
```
* `./script/index.js` に以下を記述する
```javascript
function testFunc() {
AT=RAND(1000);
JUMPGATE(RAND(100), RAND(100));
}
```
```
testFunc();
```
=> feat(wwa-expression2): 外部スクリプトファイル対応

packages/engine/src/wwa_main.ts, packages/engine/src/wwa_parts_player.ts
- キャラが動いている時に発生したゲームスピード変更
- キャラが動いている時に発生したメッセージ
- ウィンドウが開いている時に発生したジャンプゲート
- ウィンドウが開いている時に発生したメッセージ
が、動作終了時まで遅延するようになります
=> fix: moveマクロ、全種類のウィンドウ待機中に発生したリクエスト処理に対応

packages/all/scripts/make-wwawing-dist.ts, packages/engine/debug/make-debug-pages.ts, packages/engine/src/wwa_inject_html.ts, packages/engine/src/wwa_main.ts, packages/page-generator/src/data-types/wwa.ts, packages/page-generator/src/index.ts, packages/page-generator/src/wwa.pug, packages/styles/src/core/_canvas.scss, packages/styles/src/core/_debug-console.scss, packages/styles/src/core/index.scss
=> feat: デバッグコンソールはwrapperがなければ非表示, 不安定版表記追加

packages/common-interface/src/index.ts, packages/common-interface/src/wwa_data.ts, packages/common-interface/src/wwa_system_message.ts, packages/engine/src/wwa_data.ts, packages/engine/src/wwa_main.ts, packages/engine/src/wwa_message.ts, packages/engine/src/wwa_parts_player.ts, packages/loader/src/infra/index.ts
=> feat(system-message): システムメッセージをマクロで書き換えられるようにしたい

packages/engine/src/wwa_expression2/converter.ts, packages/engine/src/wwa_expression2/eval.ts, packages/engine/src/wwa_expression2/wwa.ts, packages/engine/src/wwa_main.ts
ユーザ変数・HPなど各種ステータスに代入演算子を使えるようにしました
```
HP += 10;
v[0] -= 20;
v[1] *= 2;
v[2] /= 2;
GD *= 20;
```
=> 加算演算子など、各種代入演算子を使えるようにしました

lerna.json, package-lock.json, packages/all/package.json, packages/assets/package.json, packages/common-interface/package.json, packages/debug-server/package.json, packages/engine/package.json, packages/engine/src/wwa_expression2/acorn.ts, packages/engine/src/wwa_expression2/converter.ts, packages/engine/src/wwa_expression2/eval.ts, packages/engine/src/wwa_expression2/wwa.ts, packages/engine/src/wwa_main.ts, packages/event-emitter/package.json, packages/loader/package.json, packages/page-generator/package.json, packages/styles/package.json, packages/virtual-pad/package.json
=> feat/acorn-addUserVariable-neo <- feat/acorn (2023-11-13)

packages/engine/src/wwa_vardump/index.ts
=> fix: 名前つき変数のダンプ封印

packages/engine/src/wwa_expression2/acorn.ts, packages/engine/src/wwa_expression2/converter.ts, packages/engine/src/wwa_expression2/eval.ts, packages/engine/src/wwa_expression2/wwa.ts, packages/engine/src/wwa_main.ts
```
v[0] = 0;
if(!(v[0] == 1)) {
MSG("hoge")
}
```
```
v[0] = 0;
if(!(v[0] == 0)) {
MSG("hoge")
}
```
```
v[0] = ABS(-100)
```
```
v[0] = 100;
v[1] = (v[0] == 100)? 10: 20;
```
```
v[0] = 101;
v[1] = (v[0] == 100)? 10: 20;
```
```
v[0] = GET_DATE_SECONDS();
v[1] = GET_DATE_MILLISECONDS();
v[2] = GET_DATE_WEEKDAY();
```
```
v[0] = GET_GAMEOVER_POS_X();
v[1] = GET_GAMEOVER_POS_Y();
```
=> 各種演算子を追加しました

packages/common-interface/src/wwa_system_message.ts, packages/engine/src/wwa_estimate_battle.ts, packages/engine/src/wwa_main.ts, packages/engine/src/wwa_parts_player.ts
詳細はコメント参照
https://github.com/WWAWing/WWAWing/compare/feat/acorn...fix/battle-first-turn-problem?expand=1#diff-83b5a776b948e705cc7931d6f3686e911fdd1c778afb41a67bdd92cf246bf759R1057-R1062
=> fix(battle): 攻撃無効判定の互換性担保

lerna.json, package-lock.json, packages/all/package.json, packages/assets/package.json, packages/common-interface/package.json, packages/debug-server/package.json, packages/engine/package.json, packages/event-emitter/package.json, packages/loader/package.json, packages/page-generator/package.json, packages/styles/package.json, packages/virtual-pad/package.json
This reverts commit b5cdb9edba2e42e7719000d99ed09d66e3595d3c.
#682 のプレリリースの操作ミスで develop にバージョンアップコミットが入ってしまいましたので Revert します。
=> Revert "v4.1.0-unstable.based-on.3.12.11"

packages/engine/src/wwa_message/data/node.ts
マルウェアの疑いが晴れたのでrevertしていたコードを戻します
Reverts WWAWing/WWAWing#712
=> Revert "Revert "fix(node): triggerPartsの渡し漏れを修正""

packages/engine/src/wwa_main.ts
- メッセージ中にメッセージが発生した場合に処理を吸収するのは既存の仕組みがあったので、それに乗っかることにした
- その上で、メッセージ中にメッセージが発生した場合に1フレーム待って処理するようになっており、その間にプレイヤーが動くとプレイヤーがズレた状態で次のメッセージが発生してしまうため、待たずに次の処理を実行するよう修正した
=> fix: メッセージ中にメッセージが発生した場合に同じフレームで処理を継続する

packages/engine/src/wwa_expression2/eval.ts
- `ITEM[]`, `m[][]`, `o[][]` に複合代入 `+=`, `-=`, `*=`, `/=` が効かなかったので修正します (ただし、`ITEM[0]` への複合代入は値が決められないため禁止とします)
- `v[]`, `ITEM[]`,  `m[][]`, `o[][]`  がインクリメント・デクリメントできるようになります（後置のみ） こちらも `ITEM[0]++` や `ITEM[0]--` はできません
- `%=` や前置インクリメントは他の変数に対しても有効であるべきなので今回は非対応とします
=> fix(eval): ITEM, m, o, (一部v) で複合代入ができない不具合を修正

packages/engine/src/wwa_expression2/eval.ts, packages/engine/src/wwa_main.ts
WWA Script で下記のように FACE と MSG を併用した場合に動かない不具合を修正します
close #738 
```
<script>
FACE(160, 160, 0, 1, 3, 3);
MSG("hogehoge");
```
=> fix(eval): FACE関数が使えない不具合を修正

packages/engine/src/wwa_expression2/eval.ts
マニュアルには `0` を指定すると削除できると記載がありましたが、実は未実装でした。
なのでその機能を実装します。
=> 【ピクチャ機能】 PICTURE_FROM_PARTS 関数でピクチャの削除を提供

package-lock.json
=> build(deps-dev): bump axios from 1.7.5 to 1.8.4

package-lock.json, packages/all/package.json, packages/assets/package.json, packages/common-interface/package.json, packages/debug-server/package.json, packages/engine/package.json, packages/event-emitter/package.json, packages/loader/package.json, packages/page-generator/package.json, packages/serve-index/package.json, packages/styles/package.json, packages/util/package.json, packages/virtual-pad/package.json
#798 のマージ前にバージョン表記を元に戻しておく
#798 を緊急に修正する必要があった場合のためマージは8/31実施
=> chore(npm): 超不安定版のバージョン表記をrevert
